################################################
# Copyright 2022- IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache-2.0
################################################

apiVersion: v1
kind: ConfigMap
metadata:
    name: ebpf-router-rules
    namespace: kube-system
data:
    r0: |
      type=cidr
      from="10.233.64.0/18"
      to="10.233.64.0/18"
    r1: |
      type=podLabel
      name=app-type
      value=network-intense